In [2]:
#Create input file for seismic tomography --- from the uniq quarry-station file
import pandas as pd
#import SeisBlast as sb
seisblast_files = '/home/bmelo/bin/SeisBlast/files/'

In [3]:
#Import all the necessary files
#james_catalogue = pd.read_csv('/mnt/REPO/QUARRY-BLASTS/CATALOGS/quarry-blast-catalog-2013-2014.csv', sep = r'\s+')
#james_bulletins_dir = "/mnt/REPO/QUARRY-BLASTS/BULLETINS/"
stations = pd.read_csv(
    "/home/bmelo/bin/Quarry/James_files/Total_Stations_List.txt", 
    delimiter=' ',
    header = 0,
    names=['sta', 'name','lat', 'lon', 'elevation', 'net', 'end'])
uniq_blasts = pd.read_csv('/home/bmelo/bin/SeisBlast/files/uniq_quarry-station_list.csv')
uniq_blasts
#merge with the relocated quarry blasts lists to get the relocated events
#relocated_catalogue = pd.merge(james_catalogue, relocated_blasts, left_on='EVENT-ID', right_on='id-ev')

,closest-ev_id,quarry-lat,quarry-lon,origin_time,mag,sta,closest-time,count
0,dias2013kwhe,54.3797,-7.378597,2013-06-04 11:58:42.744,1.29,"['D34', 'DL31', 'IDGL', 'UCRUI']","[13.873, 10.696, 13.043, 16.183]",5
1,dias2013kwks,52.8995,-9.038942,2013-06-04 13:45:39.377,1.56,"['IA002', 'IA009', 'IAD01', 'UCAR3', 'UD10', '...","[27.592, 18.393, 3.43, 12.756, 35.399, 24.536,...",5
2,dias2013kwle,53.4341,-7.138017,2013-06-04 14:00:17.523,1.18,['UCD11'],[10.823],5
3,dias2013kwlj,52.5985,-7.200083,2013-06-04 14:05:07.330,1.16,"['DSB', 'UHELL']","[15.376, 15.765]",5
4,dias2013kwls,53.3092,-9.007666,2013-06-04 14:16:21.183,1.71,"['DSB', 'IA009', 'IA013', 'IAD01', 'IGLA', 'UC...","[28.79, 10.624, 21.342, 10.326, 4.683, 10.139,...",5
...,...,...,...,...,...,...,...,...
1175,dias2014yqpq,54.8313,-6.050479,2014-12-17 14:56:14.298,1.26,['DL14'],[19.989],3
1176,dias2014ysgw,53.2730,-6.502024,2014-12-18 12:46:48.262,0.76,['ILTH'],[14.815],5
1177,dias2014yshe,54.2518,-6.586716,2014-12-18 12:55:53.479,0.99,['IA003'],[26.231],5
1178,dias2014yucm,54.5246,-8.088243,2014-12-19 12:50:04.704,1.09,"['DL13', 'DL24', 'IA009', 'IDGL', 'ILTH', 'UD0...","[14.473, 13.673, 15.818, 12.152, 22.142, 7.722...",5
1179,dias2014yuer,52.5482,-7.844765,2014-12-19 13:56:35.559,1.59,"['DSB', 'IA013', 'IAD38', 'UGA10', 'UGA12', 'U...","[20.664, 12.887, 15.109, 20.198, 20.664, 20.019]",5

In [4]:

#start with formating the separate date and time formats
uniq_blasts['year'] = pd.to_datetime(uniq_blasts['origin_time'], format='%Y-%m-%d %H:%M:%S.%f').dt.year
uniq_blasts['month'] = pd.to_datetime(uniq_blasts['origin_time'], format='%Y-%m-%d %H:%M:%S.%f').dt.month
uniq_blasts['day'] = pd.to_datetime(uniq_blasts['origin_time'], format='%Y-%m-%d %H:%M:%S.%f').dt.day
uniq_blasts['hour'] = pd.to_datetime(uniq_blasts['origin_time'], format='%Y-%m-%d %H:%M:%S.%f').dt.hour
uniq_blasts['minute'] = pd.to_datetime(uniq_blasts['origin_time'], format='%Y-%m-%d %H:%M:%S.%f').dt.minute
uniq_blasts['second'] = pd.to_datetime(uniq_blasts['origin_time'], format='%Y-%m-%d %H:%M:%S.%f').dt.second + pd.to_datetime(uniq_blasts['origin_time'], format='%Y-%m-%d %H:%M:%S.%f').dt.microsecond / 1e6
#uniq_blasts['depth-quarry'] = 0

In [5]:
#Source line : id_src year month day hour min sec lat lon dep_km magnitude num_recs id_event (weight)
#Currently building it up with only P phases !!!!

# Open the file in write mode to ensure it's empty before starting the loop
with open(seisblast_files + '/seismic_tomography_uniqinput_P.txt', 'w') as f:
    f.write("")
    
for index_src in range(len(uniq_blasts)):
    
    #loop over the rows in the dataframe
    len_rec = len(eval(uniq_blasts['sta'].iloc[index_src]))
    #print(str(uniq_blasts['count'].iloc[index_src]))
    with open(seisblast_files + '/seismic_tomography_uniqinput_P.txt', 'a') as f:
        f.write(
            f"{index_src:<8}"
            f"{uniq_blasts['year'].iloc[index_src]:<8}"
            f"{uniq_blasts['month'].iloc[index_src]:<8}"
            f"{uniq_blasts['day'].iloc[index_src]:<8}"
            f"{uniq_blasts['hour'].iloc[index_src]:<8}"
            f"{uniq_blasts['minute'].iloc[index_src]:<8}"
            f"{uniq_blasts['second'].iloc[index_src]:<12.2f}"
            f"{uniq_blasts['quarry-lat'].iloc[index_src]:<12}"
            f"{uniq_blasts['quarry-lon'].iloc[index_src]:<12}"
            f"{'0':<12}"
            f"{uniq_blasts['mag'].iloc[index_src]:<12}"
            f"{str(len_rec):<12}"
            f"{uniq_blasts['closest-ev_id'].iloc[index_src]:<12}\n"
        )
        
        #loop over the items in each row
        for index_rec in range(len_rec):
            #fetch station information
            st=eval(uniq_blasts['sta'].iloc[index_src])[index_rec]
            station_info = stations[stations['name'] == st]
            #write the receiver lines to file
            f.write(
                f"{index_src:<8}"
                f"{index_rec:<8}"
                f"{st:<10}"
                f"{station_info['lat'].item():<12}"
                f"{station_info['lon'].item():<12}"
                f"{station_info['elevation'].item():<12}"
                f"{'P':<8}"
                f"{eval(uniq_blasts['closest-time'].iloc[index_src])[index_rec]:<12}\n"
            )